POST http://localhost:3333/videos
Content-Type: application/json

    {
        "title": "video 1",
        "description": "video 1 description",
        "duration": 180 
    }

###
// GET SEM QUERY PARAMS

GET http://localhost:3333/videos

###
// GET COM QUERY PARAMS

GET http://localhost:3333/videos?search=video 1

###

PUT http://localhost:3333/videos/84443489-882e-4838-844c-df8ad3e559b0
Content-Type: application/json
Accept-Language: pt-BR

{
    "title": "video 10 atualizado",
    "description": "video 10 description atualizado",
    "duration": 180 
}

###

DELETE http://localhost:3333/videos/9878cfd2-cbfe-4064-9454-14b09807e8eb


