POST https://node-fastify-hsgj.onrender.com/videos
Content-Type: application/json

    {
        "title": "video 1",
        "description": "video 1 description",
        "duration": 180 
    }

###
// GET SEM QUERY PARAMS

GET https://node-fastify-hsgj.onrender.com/videos

###
// GET COM QUERY PARAMS

GET https://node-fastify-hsgj.onrender.com/videos?search=video 1

###

PUT https://node-fastify-hsgj.onrender.com/videos/84443489-882e-4838-844c-df8ad3e559b0
Content-Type: application/json
Accept-Language: pt-BR

{
    "title": "video 9 atualizado",
    "description": "video 9 description atualizado",
    "duration": 180 
}

###

DELETE https://node-fastify-hsgj.onrender.com/videos/9878cfd2-cbfe-4064-9454-14b09807e8eb


